language: go
addons:
    apt:
        packages:
            - git
            - freetds-dev
            - g++
go:
    - master

before_install:
    - go get -v github.com/labstack/echo
    - go get -v github.com/dgrijalva/jwt-go
    - go get -v github.com/minus5/gofreetds
    - go get -v github.com/Masterminds/squirrel
    - mkdir $GOPATH/log
