sudo: required

language: go

services:
    - docker
addons:
    apt:
        packages:
            - git
            - freetds-dev
            - g++
go:
    - master

before_install:
    - go get -v github.com/dgrijalva/jwt-go
    - go get -v github.com/minus5/gofreetds
    - go get -v github.com/Masterminds/squirrel
    - mkdir $GOPATH/log

after_success:
    - docker build -t penutty/authservice .
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push penutty/authservice
